name: drop_animation
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/mustafakilic097/drop_animation.git"
repository: "https://github.com/mustafakilic097/drop_animation.git"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true